import { useState } from 'react';
import { toast } from 'sonner';
import { BrevitaResponse } from '../types';
import { ShieldAlert, Info, List, Clock, Target, Eye, Zap, Activity, Share2, Copy, Check, Twitter, Download, FileText, Map, Globe, Printer, FileCode, ExternalLink } from 'lucide-react';
import { UI_TRANSLATIONS } from '../constants';
import { generatePrintableHtml } from '../services/printService';

interface AnalysisViewProps {
  data: BrevitaResponse;
}

const AnalysisView = ({ data }: AnalysisViewProps) => {
  const isMilitary = data.military_mode?.is_included;
  const [copied, setCopied] = useState(false);

  // Determine language safely
  const rawLang = data.meta.output_language?.toUpperCase() || 'EN';
  const lang = (rawLang in UI_TRANSLATIONS ? rawLang : 'EN') as keyof typeof UI_TRANSLATIONS;
  const t = UI_TRANSLATIONS[lang];

  const generateShareableText = () => {
    const { meta, summary_30s, key_points } = data;
    return `BREVITA INTEL BRIEF\n\n` +
      `📄 ${meta.title}\n` +
      `📅 ${meta.date || 'N/A'} | ⏱️ ${meta.estimated_reading_time_seconds}s Read\n\n` +
      `SUMMARY:\n${summary_30s}\n\n` +
      `KEY POINTS:\n${key_points.map(p => `• ${p}`).join('\n')}\n\n` +
      `Generated by Brevita.ai`;
  };

  const generateMarkdown = () => {
    const { meta, summary_30s, key_points, context_notes, bias_or_uncertainty, military_mode } = data;
    let md = `# ${meta.title || 'Intelligence Briefing'}\n\n` +
      `**Date:** ${meta.date || 'N/A'}\n` +
      `**Source:** ${meta.source || 'Unknown'}\n` +
      `**Reading Time:** ${meta.estimated_reading_time_seconds} seconds\n\n` +
      `## Executive Summary\n${summary_30s}\n\n` +
      `## Key Points\n${key_points.map(p => `- ${p}`).join('\n')}\n\n` +
      `## Context\n${context_notes}\n\n` +
      `## Bias Assessment\n${bias_or_uncertainty}\n\n`;

    if (military_mode?.is_included) {
      md += `## Military & OSINT Analysis\n` +
        `**Risk Level:** ${military_mode.risk_level || 'N/A'}\n\n` +
        `**Commander's Brief:**\n${military_mode.commander_brief}\n\n` +
        `### Actors\n${military_mode.actors.join(', ')}\n\n` +
        `### Objectives\n${military_mode.interests_and_objectives}\n\n` +
        `### Risks & Threats\n${military_mode.risks_and_threats}\n\n` +
        `### Operational Implications\n${military_mode.operational_implications}\n\n` +
        `### Watchpoints\n${military_mode.watchpoints_for_commanders.map(w => `- ${w}`).join('\n')}\n`;
    }

    if (data.groundingChunks && data.groundingChunks.length > 0) {
      md += `\n## Verified Sources\n`;
      data.groundingChunks.forEach(chunk => {
        if (chunk.web) {
          md += `- [${chunk.web.title}](${chunk.web.uri})\n`;
        }
      });
    }

    return md;
  };

  const handleDownload = (format: 'md' | 'txt' | 'html') => {
    let content = '';
    let mimeType = 'text/plain';
    let extension = format;

    if (format === 'md') {
      content = generateMarkdown();
    } else if (format === 'txt') {
      content = generateShareableText();
    } else if (format === 'html') {
      content = data.pdf_html || '<html><body><h1>Error: No HTML content generated.</h1></body></html>';
      mimeType = 'text/html';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `brevita-briefing-${Date.now()}.${extension}`;
    await navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  } catch (err) {
    console.error('Failed to copy', err);
    toast.error("Failed to copy to clipboard");
  }
};

const handleNativeShare = async () => {
  const text = generateShareableText();
  if (navigator.share) {
    try {
      await navigator.share({
        title: data.meta.title,
        text: text,
      });
    } catch (err) {
      if ((err as any).name !== 'AbortError') {
        console.error('Error sharing', err);
        toast.error("Failed to share");
      }
    }
  } else {
    handleCopy();
  }
};

const handleTweet = () => {
  const text = `${data.meta.title}\n\n${data.summary_30s.substring(0, 180)}...\n\nAnalysis via Brevita.ai`;
  window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`, '_blank');
};

return (
  <div className="animate-fade-in space-y-8 pb-12">
    {/* Header Info */}
    <div className="border-b border-slate-200 dark:border-slate-700 pb-6">
      <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-6">
        <div className="flex-1">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-white leading-tight">
            {data.meta.title || "Untitled Intelligence Brief"}
          </h1>
          <div className="flex flex-wrap items-center gap-4 mt-3 text-sm text-slate-500 dark:text-slate-400 font-medium uppercase tracking-wider">
            {data.meta.source && (
              <span className="bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 px-2 py-1 rounded">
                {data.meta.source}
              </span>
            )}
            {data.meta.date && <span>{data.meta.date}</span>}
            <div className="flex items-center gap-1 text-indigo-600 dark:text-indigo-400">
              <Clock size={16} />
              <span>{data.meta.estimated_reading_time_seconds}s {t.read_time}</span>
            </div>
            {data.meta.category && (
              <span className="bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-300 px-2 py-1 rounded border border-indigo-100 dark:border-indigo-800">
                {data.meta.category}
              </span>
            )}
            {data.meta.region && (
              <span className="bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2 py-1 rounded border border-slate-200 dark:border-slate-700 flex items-center gap-1">
                <Globe size={14} />
                {data.meta.region}
              </span>
            )}
            {data.meta.country && (
              <span className="bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2 py-1 rounded border border-slate-200 dark:border-slate-700 flex items-center gap-1">
                <Map size={14} />
                {data.meta.country}
              </span>
            )}
            {data.meta.tags?.map((tag, i) => (
              <span key={i} className="text-xs text-slate-400 dark:text-slate-500 lowercase">
                #{tag}
              </span>
            ))}
            {isMilitary && (
              <span className="flex items-center gap-1 bg-amber-100 dark:bg-amber-900/40 text-amber-800 dark:text-amber-300 px-2 py-1 rounded border border-amber-200 dark:border-amber-800/50">
                <ShieldAlert size={14} /> {t.military_mode}
              </span>
            )}
          </div>
        </div>

        {/* Share Toolbar */}
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-lg border border-slate-200 dark:border-slate-700 mr-2">
            <button onClick={() => handleDownload('html')} className="p-2 text-slate-600 dark:text-slate-400 hover:text-indigo-600 hover:bg-white dark:hover:bg-slate-700 rounded-md transition-all" title="Download HTML Source">
              <FileCode size={18} /> <span className="sr-only">HTML</span>
            </button>
            <button onClick={() => handleDownload('md')} className="p-2 text-slate-600 dark:text-slate-400 hover:text-indigo-600 hover:bg-white dark:hover:bg-slate-700 rounded-md transition-all" title="Export Markdown">
              <Download size={18} /> <span className="sr-only">MD</span>
            </button>
            <button onClick={() => handleDownload('txt')} className="p-2 text-slate-600 dark:text-slate-400 hover:text-indigo-600 hover:bg-white dark:hover:bg-slate-700 rounded-md transition-all" title="Export Text">
              <FileText size={18} /> <span className="sr-only">TXT</span>
            </button>
          </div>

          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 hover:text-indigo-600 dark:hover:text-indigo-400 transition-all"
            title="Export PDF"
          >
            <Printer size={18} />
            <span className="hidden sm:inline">PDF</span>
          </button>

          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 hover:text-indigo-600 dark:hover:text-indigo-400 transition-all"
            title="Copy Briefing"
          >
            {copied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
            <span className="hidden sm:inline">{copied ? 'Copied' : 'Copy'}</span>
          </button>

          <button
            onClick={handleTweet}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-sky-50 dark:hover:bg-slate-700 hover:text-sky-500 transition-all"
            title="Share on X (Twitter)"
          >
            <Twitter size={18} />
            <span className="hidden sm:inline">Tweet</span>
          </button>

          <button
            onClick={handleNativeShare}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium bg-indigo-600 dark:bg-indigo-600 text-white hover:bg-indigo-700 dark:hover:bg-indigo-500 shadow-sm transition-all"
            title="Share"
          >
            <Share2 size={18} />
            <span className="hidden sm:inline">Share</span>
          </button>
        </div>
      </div>
    </div>

    {/* Main 2-Column Grid */}
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
      {/* Left Column: Summary & Context */}
      <div className="lg:col-span-2 space-y-8">

        {/* Executive Summary */}
        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
            <Zap className="text-yellow-500" size={20} />
            {t.executive_summary}
          </h2>
          <div className="prose prose-slate dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 leading-relaxed text-lg">
            {data.summary_30s.split('\n').map((para, i) => (
              <p key={i}>{para}</p>
            ))}
          </div>
        </section>

        {/* Context & Bias Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-blue-50 dark:bg-blue-900/20 p-5 rounded-xl border border-blue-100 dark:border-blue-900/50">
            <h3 className="text-blue-900 dark:text-blue-100 font-semibold mb-2 flex items-center gap-2">
              <Info size={18} /> {t.context}
            </h3>
            <p className="text-blue-800 dark:text-blue-200 text-sm leading-relaxed">
              {data.context_notes}
            </p>
          </div>
          <div className="bg-slate-50 dark:bg-slate-800/50 p-5 rounded-xl border border-slate-200 dark:border-slate-700">
            <h3 className="text-slate-900 dark:text-white font-semibold mb-2 flex items-center gap-2">
              <Target size={18} /> {t.bias_check}
            </h3>
            <p className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed italic">
              "{data.bias_or_uncertainty}"
            </p>
          </div>
        </div>

        {/* Key Points */}
        <section>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
            <List className="text-indigo-500 dark:text-indigo-400" size={20} />
            {t.key_points}
          </h2>
          <ul className="space-y-3">
            {data.key_points.map((point, idx) => (
              <li key={idx} className="flex items-start gap-3 text-slate-700 dark:text-slate-300">
                <span className="flex-shrink-0 w-1.5 h-1.5 rounded-full bg-indigo-500 dark:bg-indigo-400 mt-2.5" />
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* Grounding/Search Sources */}
        {data.groundingChunks && data.groundingChunks.length > 0 && (
          <section className="bg-slate-50 dark:bg-slate-800/50 p-5 rounded-xl border border-slate-200 dark:border-slate-700">
            <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest mb-3 flex items-center gap-2">
              <Globe size={16} /> {t.verified_sources}
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {data.groundingChunks.map((chunk, i) => (
                chunk.web ? (
                  <a
                    key={i}
                    href={chunk.web.uri}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 p-2 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-indigo-400 dark:hover:border-indigo-500 transition-colors group"
                  >
                    <ExternalLink size={14} className="text-slate-400 group-hover:text-indigo-500" />
                    <span className="text-sm text-slate-700 dark:text-slate-300 truncate">{chunk.web.title}</span>
                  </a>
                ) : null
              ))}
            </div>
          </section>
        )}

      </div>

      {/* Right Column: Military Dashboard (Conditional) or Standard Meta */}
      <div className="space-y-6">
        {isMilitary ? (
          <MilitaryPanel data={data.military_mode} lang={lang} />
        ) : (
          <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm">
            <h3 className="text-sm font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-4">{t.standard_analysis}</h3>
            <p className="text-slate-500 dark:text-slate-400 text-sm">
              {t.standard_analysis_desc}
            </p>
          </div>
        )}
      </div>
    </div>
  </div>
);
};

const MilitaryPanel = ({ data, lang }: { data: BrevitaResponse['military_mode'], lang: keyof typeof UI_TRANSLATIONS }) => {
  const t = UI_TRANSLATIONS[lang];

  const getRiskColor = (risk: string) => {
    const r = risk?.toUpperCase() || 'LOW';
    if (r.includes('HIGH')) return 'text-red-500 bg-red-500/10 border-red-500/20';
    if (r.includes('MEDIUM')) return 'text-amber-500 bg-amber-500/10 border-amber-500/20';
    return 'text-green-500 bg-green-500/10 border-green-500/20';
  };

  return (
    <div className="bg-slate-900 text-slate-100 rounded-xl overflow-hidden shadow-xl border border-slate-700">
      <div className="bg-slate-800 px-5 py-3 border-b border-slate-700 flex items-center justify-between">
        <h3 className="font-mono text-sm font-bold tracking-widest text-amber-500 flex items-center gap-2">
          <ShieldAlert size={16} />
          {t.osint_dashboard}
        </h3>
        <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
      </div>

      <div className="p-5 space-y-6 text-sm">

        {/* Risk Level & Commander Brief */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 text-xs uppercase font-mono">{t.threat_level}</span>
            <span className={`px-2 py-0.5 rounded text-xs font-bold border ${getRiskColor(data.risk_level)}`}>
              {data.risk_level || 'UNKNOWN'}
            </span>
          </div>

          <div className="bg-slate-800/80 p-3 rounded border-l-2 border-amber-500">
            <h4 className="text-amber-500 font-mono text-[10px] uppercase mb-1 flex items-center gap-1">
              <Zap size={10} /> {t.commanders_brief}
            </h4>
            <p className="text-slate-200 font-medium leading-snug italic">
              "{data.commander_brief || 'No brief generated.'}"
            </p>
          </div>
        </div>

        {/* Theaters & Domains */}
        <div>
          <div className="flex flex-wrap gap-2 mb-2">
            {data.theater_tags?.map((tag, i) => (
              <span key={i} className="flex items-center gap-1 bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded text-[10px] border border-slate-700 uppercase">
                <Globe size={10} /> {tag}
              </span>
            ))}
            {data.domain_tags?.map((tag, i) => (
              <span key={i} className="flex items-center gap-1 bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded text-[10px] border border-slate-700 uppercase">
                <Map size={10} /> {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Actors */}
        <div>
          <h4 className="text-slate-400 font-mono text-xs uppercase mb-2">{t.key_actors}</h4>
          <div className="flex flex-wrap gap-2">
            {data.actors.map((actor, i) => (
              <span key={i} className="bg-slate-800 text-slate-200 px-2 py-1 rounded text-xs border border-slate-700">
                {actor}
              </span>
            ))}
          </div>
        </div>

        {/* Objectives */}
        <div>
          <h4 className="text-slate-400 font-mono text-xs uppercase mb-2">{t.objectives}</h4>
          <p className="text-slate-300 leading-relaxed font-light border-l-2 border-slate-600 pl-3">
            {data.interests_and_objectives}
          </p>
        </div>

        {/* Risks */}
        <div>
          <h4 className="text-slate-400 font-mono text-xs uppercase mb-2">{t.risks}</h4>
          <p className="text-red-300 leading-relaxed font-light bg-red-900/10 p-2 rounded">
            {data.risks_and_threats}
          </p>
        </div>

        {/* Implications */}
        <div>
          <h4 className="text-slate-400 font-mono text-xs uppercase mb-2">{t.implications}</h4>
          <p className="text-slate-300 font-light">{data.operational_implications}</p>
        </div>

        {/* Tech */}
        {data.tech_and_AI_relevance && (
          <div>
            <h4 className="text-slate-400 font-mono text-xs uppercase mb-2 flex items-center gap-2">
              <Activity size={12} /> {t.tech_cyber}
            </h4>
            <p className="text-cyan-300 font-light text-xs">{data.tech_and_AI_relevance}</p>
          </div>
        )}

        {/* Watchpoints */}
        <div className="bg-slate-800/50 p-3 rounded border border-slate-700/50">
          <h4 className="text-amber-500 font-mono text-xs uppercase mb-2 flex items-center gap-2">
            <Eye size={14} /> {t.watchpoints}
          </h4>
          <ul className="space-y-2">
            {data.watchpoints_for_commanders.map((wp, i) => (
              <li key={i} className="flex items-start gap-2 text-slate-300 font-mono text-xs">
                <span className="text-slate-600">[{i + 1}]</span>
                {wp}
              </li>
            ))}
          </ul>
        </div>

      </div>
    </div>
  );
};

export default AnalysisView;